export const DASHBOARD = '/'
export const LOGIN = '/login'
export const PROFILE = '/:profile'
export const NOT_FOUND = '/not-found'
export const INBOX = '/direct/inbox/'
export const EXPLORE = '/explore'
export const SIGNUP = '/signup'
export const USER_TOKEN = 'user-token'
