import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import User from '../../models/User';
import connectToDb from '../../lib/connectToDb';
import Post from '../../models/Post';

export default function Home({ user, userPosts }) {
  console.log(user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{JSON.stringify(user)}</p>
        <p>
          <br></br>
        </p>
        <p>{JSON.stringify(userPosts)}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const userQuery = context.query.username;

  await connectToDb();

  const user = await User.findOne({ username: userQuery });
  const userPosts = await Post.findOne({ username: userQuery });

  return {
    props: {
      user: JSON.parse(JSON.stringify(user)),
      userPosts: JSON.parse(JSON.stringify(userPosts)),
    },
  };
}
